version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9292:9292
    command: bundle exec rackup -o0
    volumes:
      - ./memos:/app/memos
      # - ./.tantiny:/app/.tantiny reenable with matching uid/guid
    restart: unless-stopped
