---
id: 2021/08/21/hgfe-dcba
title: Facts about Pugs!
tags: dog,pug,pet
urls:
  - http://localhost:9292/memos/2021/08/21/hgfe-dcba
  - http://localhost:9292/memos/2021/08/21/hgfe-dcba/edit
updated_at: !ruby/object:DateTime 2022-09-29 17:29:58.161601000 +02:00
